on: [workflow_call]

name: Check

permissions: {}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      -
        name: Set up Go
        uses: actions/setup-go@v7
        with:
          cache: false
          go-version-file: src/go.mod

      -
        name: Generate Go module files
        working-directory: src
        run: |
          set -Eeuo pipefail

          go mod tidy

          echo "===== BEGIN src/go.mod ====="
          cat go.mod
          echo "===== END src/go.mod ====="

          echo "===== BEGIN src/go.sum ====="
          cat go.sum
          echo "===== END src/go.sum ====="

          echo "===== MODULE DIFF ====="
          git diff -- go.mod go.sum || true

      -
        name: Check Go syntax
        run: |
          find . -type f -name '*.go' -print0 |
            xargs -0 -r -n 1 gofmt -e >/dev/null
        working-directory: src

      -
        name: Check Go module syntax
        run: go mod edit -json >/dev/null
        working-directory: src

      -
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.4.0
        with:
          dockerfile: Dockerfile
          ignore: DL3008,DL3018
          failure-threshold: warning
