on: [workflow_call]

name: Check

permissions: {}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      -
        name: Set up Go
        uses: actions/setup-go@v7
        with:
          cache: false
          go-version-file: src/go.mod

      -
        name: Check Go syntax
        run: |
          find . -type f -name '*.go' -print0 |
            xargs -0 -r -n 1 gofmt -e >/dev/null
        working-directory: src

      -
        name: Check Go module syntax
        run: go mod edit -json >/dev/null
        working-directory: src

      -
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
          ignore: DL3008
          failure-threshold: warning
